class Song(object):
    def __init__(self, lyrics):
        self.lyrics = lyrics
    
    def sing_me_a_song(self):
        for line in self.lyrics:
            print line

get_lucky_lyrics = ["Like the legend of the phoenix",
                    "All ends with beginnings",
                    "What keeps the planet spinning (uh)",
                    "The force of love beginning",
                    "We've come too far to give up who we are",
                    "So let's raise the bar and our cups to the stars",
                    "She's up all night 'til the sun",
                    "I'm up all night to get some",
                    "She's up all night for good fun",
                    "I'm up all night to get lucky",
                    "We're up all night 'til the sun",
                    "We're up all night to get some",
                    "We're up all night for good fun",
                    "We're up all night to get lucky",
                    "We're up all night to get lucky",
                    "We're up all night to get lucky",
                    "We're up all night to get lucky",
                    "We're up all night to get lucky",
                    "The present has no ribbon",
                    "Your gift keeps on giving,",
                    "What is this I'm feeling?",
                    "If you wanna leave I'm with it (ah)",
                    "We've come too far to give up who we are",
                    "So let's raise the bar and our cups to the stars",
                    "She's up all night 'til the sun",
                    "I'm up all night to get some",
                    "She's up all night for good fun",
                    "I'm up all night to get lucky",
                    "We're up all night 'til the sun",
                    "We're up all night to get some",
                    "We're up all night for good fun",
                    "We're up all night to get lucky",
                    "We're up all night to get lucky",
                    "We're up all night to get lucky",
                    "We're up all night to get lucky",
                    "We're up all night to get lucky",
                    "We've come too far to give up who we are",
                    "So let's raise the bar and our cups to the stars",
                    "She's up all night 'til the sun",
                    "I'm up all night to get some",
                    "She's up all night for good fun",
                    "I'm up all night to get lucky",
                    "We're up all night 'til the sun",
                    "We're up all night to get some",
                    "We're up all night for good fun",
                    "We're up all night to get lucky",
                    "We're up all night to get lucky",
                    "We're up all night to get lucky",
                    "We're up all night to get lucky",
                    "We're up all night to get lucky",
                    "We're up all night to get lucky",
                    "We're up all night to get lucky",
                    "We're up all night to get lucky",
                    "We're up all night to get lucky"]

bohemian_rhapsody_lyrics = ["Is this the real life? Is this just fantasy?",
                            "Caught in a landslide, no escape from reality",
                            "Open your eyes, look up to the skies and see",
                            "I'm just a poor boy, I need no sympathy",
                            "Because I'm easy come, easy go, little high, little low",
                            "Any way the wind blows doesn't really matter to me, to me",
                            "Mama, just killed a man",
                            "Put a gun against his head",
                            "Pulled my trigger, now he's dead",
                            "Mama, life had just begun",
                            "But now I've gone and thrown it all away",
                            "Mama, ooh, didn't mean to make you cry",
                            "If I'm not back again this time tomorrow",
                            "Carry on, carry on as if nothing really matters",
                            "Too late, my time has come",
                            "Sends shivers down my spine, body's aching all the time",
                            "Goodbye, everybody, I've got to go",
                            "Gotta leave you all behind and face the truth",
                            "Mama, ooh, I don't want to die",
                            "I sometimes wish I'd never been born at all",
                            "I see a little silhouetto of a man",
                            "Scaramouche, Scaramouche, will you do the Fandango",
                            "Thunderbolt and lightning, very, very fright'ning me",
                            "(Galileo) Galileo, (Galileo) Galileo, Galileo figaro magnifico",
                            "(I'm just a poor boy, nobody loves me)",
                            "He's just a poor boy from a poor family",
                            "Spare him his life from this monstrosity",
                            "Easy come, easy go, will you let me go?",
                            "Bismillah! No, we will not let you go",
                            "(Let him go) Bismillah! We will not let you go",
                            "(Let him go) Bismillah! We will not let you go",
                            "(Let me go) Will not let you go",
                            "(Let me go) Will not let you go",
                            "(Let me go) Ah, no, no, no, no, no, no, no",
                            "(Oh mamma mia, mamma mia) Mama mia, let me go",
                            "Beelzebub has a devil put aside for me, for me, for me",
                            "So you think you can stone me and spit in my eye?",
                            "So you think you can love me and leave me to die?",
                            "Oh, baby, can't do this to me, baby!",
                            "Just gotta get out, just gotta get right outta here!",
                            "Nothing really matters, anyone can see",
                            "Nothing really matters",
                            "Nothing really matters to me",
                            "Any way the wind blows"]

get_lucky = Song(get_lucky_lyrics)

bohemian_rhapsody = Song(bohemian_rhapsody_lyrics)

print "=" * 50
get_lucky.sing_me_a_song()

print "=" * 50
bohemian_rhapsody.sing_me_a_song()
